export const UPDATE_POST = 'UPDATE_POST';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const LOG_OUT = 'LOG_OUT';
export const EDIT_SUCCESS_USER = 'EDIT_SUCCESS_USER';
export const EDIT_FAILED_USER = 'EDIT_FAILED_USER';
export const CREATE_POST = 'CREATE_POST';

//user profile
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//friends
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
